# Generated by Django 5.2.3 on 2025-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=80)),
                ('horas_trabalhadas', models.IntegerField()),
                ('telefone_funcionario', models.CharField(verbose_name=15)),
            ],
        ),
    ]
