# Generated by Django 5.2.3 on 2025-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone_funcionario',
            field=models.CharField(max_length=15),
        ),
    ]
