# Generated by Django 5.2.3 on 2025-06-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=80)),
                ('employee', models.ManyToManyField(related_name='production', to='core.funcionario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='core.product')),
            ],
        ),
    ]
